# Generated by Django 5.2.4 on 2025-07-15 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_message', models.TextField(help_text='The original message from the user')),
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the task was created')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_proces_created_bfe79c_idx'), models.Index(fields=['task_id'], name='core_proces_task_id_731c7e_idx'), models.Index(fields=['status'], name='core_proces_status_132633_idx')],
            },
        ),
    ]
