apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mango-chart.fullname" . }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mango
      tier: web
  template:
    metadata:
      labels:
        app: mango
        tier: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.env.ALLOWED_HOSTS | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
